name = "YHS"
author = "Cwavs"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "55b8fc2e2cec2b93f8b4601a5002b6b66e98b46f9eb224651b0bb64596fdce86"

[versions]
fabric = "0.14.21"
minecraft = "1.20"
